# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peer_review", "0001_initial"),
        ("peer_course", "0001_initial"),
        ("peer_assignment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentquestion",
            name="rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peer_review.Rubric",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="peer_course.Course"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submissioncomponent",
            unique_together=set([("submission", "question")]),
        ),
    ]
