# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peer_course", "0001_initial"),
        ("peer_assignment", "0002_auto_20180810_1030"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="assignmentsubmission",
            unique_together=set([("assignment", "author", "calibration_id")]),
        )
    ]
