# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0003_auto_20180810_1115")]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("form", "Free Form"),
                    ("text", "Text"),
                    ("quiz", "Quiz"),
                ],
                db_column="assignment_type",
                default="pdf",
                max_length=16,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentquestionmultiplechoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="peer_assignment.AssignmentQuestion",
            ),
        ),
    ]
