# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0006_assignmentsubmission_attempts")]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="max_attempts",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="qualification_grade",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
