# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0008_auto_20180926_1050")]

    operations = [
        migrations.AlterField(
            model_name="assignmentquestion",
            name="description",
            field=models.TextField(verbose_name="Question Description"),
        )
    ]
