# Generated by Django 2.1.5 on 2019-01-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0011_auto_20190112_2029")]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="grace_hours",
            field=models.FloatField(
                blank=True, default=0, verbose_name="# of Grace hours"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_late_units",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name="Max Late Days allowed"
            ),
        ),
    ]
