# Generated by Django 2.1.5 on 2019-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0012_auto_20190126_1625")]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="submission_required",
            field=models.BooleanField(blank=True, default=True),
        )
    ]
