# Generated by Django 2.1.5 on 2019-08-13 20:55

from django.db import migrations, models


def print_warning(apps, schema_editor):
    print(
        "\n\n -------------------\n\n"
        "Please populate the submission grades before proceeding"
        "\n\n -------------------\n\n"
    )


class Migration(migrations.Migration):

    dependencies = [("peer_assignment", "0013_assignment_submission_required")]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="final_grade",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="final_grading_method",
            field=models.TextField(blank=True, default="[ungraded]", null=True),
        ),
        migrations.RunPython(print_warning),
    ]

