# Generated by Django 2.1.15 on 2021-01-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assignment', '0015_assignment_max_total_grade_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='spotchecking_priority',
            field=models.FloatField(db_column='spotcheckingpriority', default=None, verbose_name='Spotchecking Priority'),
        ),
    ]
