# Generated by Django 2.1.15 on 2021-01-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assignment', '0018_auto_20210121_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='spotchecking_priority',
        ),
    ]
