# Generated by Django 2.1.15 on 2021-01-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assignment', '0019_remove_assignmentsubmission_spotchecking_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='spotchecking_priority',
            field=models.FloatField(db_column='spotcheckingpriority', default=20, verbose_name='Spotchecking Priority'),
        ),
    ]
