# Generated by Django 2.1.15 on 2021-02-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_assignment', '0020_assignmentsubmission_spotchecking_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='spotchecking_priority',
            field=models.FloatField(db_column='spotcheckingpriority', default=1000, verbose_name='Spotchecking Priority'),
        ),
    ]
