# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 17:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("peer_course", "0001_initial"),
        ("peer_assignment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            django.core.validators.MinLengthValidator(20),
                        ]
                    ),
                ),
                ("response", models.TextField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Open"),
                            (1, "Resolved"),
                            (2, "In progress"),
                            (3, "Closed"),
                        ]
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peer_course.CourseMember",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peer_assignment.AssignmentSubmission",
                    ),
                ),
            ],
        )
    ]
