# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 22:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peer_review", "0007_auto_20181103_1451"),
        ("peer_course", "0003_coursemember_qualified"),
        ("peer_grade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InaptFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            django.core.validators.MinLengthValidator(4),
                        ]
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flagger",
                        to="peer_course.CourseMember",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag",
                        to="peer_review.ReviewAssignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InaptReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(200),
                            django.core.validators.MinLengthValidator(4),
                        ]
                    ),
                ),
                ("closed", models.BooleanField(db_index=True, default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("modification_date", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_assignee",
                        to="peer_course.CourseMember",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inapt_reporter",
                        to="peer_course.CourseMember",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peer_review.ReviewAssignment",
                    ),
                ),
            ],
        ),
    ]
