# Generated by Django 2.1.5 on 2019-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_grade", "0002_inaptflag_inaptreport")]

    operations = [
        migrations.AlterField(
            model_name="appeal",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="appeal",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Open"),
                    (1, "Resolved"),
                    (2, "In progress"),
                    (3, "Closed"),
                ],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="inaptflag",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="inaptreport",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
