# Generated by Django 2.1.5 on 2019-09-30 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grade', '0003_auto_20190112_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='request',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), django.core.validators.MinLengthValidator(20)]),
        ),
    ]
