# Generated by Django 2.1.5 on 2019-10-01 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grade', '0004_auto_20190930_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inaptreport',
            name='reason',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
