# Generated by Django 2.1.5 on 2019-10-02 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grade', '0005_auto_20191001_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='request',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(20)]),
        ),
    ]
