# Generated by Django 2.1.5 on 2019-10-02 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grade', '0006_auto_20191002_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='request',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000), django.core.validators.MinLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='inaptreport',
            name='reason',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), django.core.validators.MinLengthValidator(200)]),
        ),
    ]
