# Generated by Django 2.1.15 on 2021-03-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_grade', '0007_auto_20191002_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='timer',
            field=models.FloatField(blank=True, db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='inaptreport',
            name='timer',
            field=models.FloatField(blank=True, db_index=True, default=False),
        ),
    ]
