# Generated by Django 2.1.15 on 2023-09-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0003_poll_answer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
