# Generated by Django 2.1.15 on 2023-09-02 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0004_poll_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='used',
        ),
        migrations.AddField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
