# Generated by Django 2.1.15 on 2023-09-02 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0005_auto_20230902_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date',
        ),
        migrations.AddField(
            model_name='poll',
            name='use_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
