# Generated by Django 2.1.15 on 2023-09-02 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0007_auto_20230902_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peer_lecture.Lecture'),
        ),
    ]
