# Generated by Django 2.1.15 on 2023-09-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0009_poll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
