# Generated by Django 2.1.15 on 2023-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0011_auto_20230907_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='date',
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Title', max_length=200),
            preserve_default=False,
        ),
    ]
