# Generated by Django 2.1.15 on 2023-09-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0012_auto_20230907_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='hide_instructor',
            new_name='hide',
        ),
    ]
