# Generated by Django 2.1.15 on 2023-09-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0013_auto_20230909_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='hide',
            new_name='hidden',
        ),
    ]
