# Generated by Django 2.1.15 on 2023-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0015_message_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='enable_messages',
            field=models.BooleanField(default=False),
        ),
    ]
