# Generated by Django 2.1.15 on 2023-10-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0027_auto_20230116_1622'),
        ('peer_lecture', '0016_lecture_enable_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='course',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='peer_course.Course'),
            preserve_default=False,
        ),
    ]
