# Generated by Django 2.1.15 on 2023-10-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_lecture', '0017_poll_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='enable_messages',
            field=models.BooleanField(default=True),
        ),
    ]
