# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_course", "0002_coursemember_is_independent")]

    operations = [
        migrations.AddField(
            model_name="coursemember",
            name="qualified",
            field=models.BooleanField(default=False),
        )
    ]
