# Generated by Django 2.1.5 on 2019-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_course", "0003_coursemember_qualified")]

    operations = [
        migrations.AlterField(
            model_name="coursemember",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="qualified",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
