# Generated by Django 2.1.5 on 2019-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_course", "0004_auto_20190112_1648")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="archived",
            field=models.BooleanField(
                db_column="archived", db_index=True, verbose_name="Archived?"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="browsable",
            field=models.BooleanField(
                db_column="browsable",
                db_index=True,
                verbose_name="Visible to Students?",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor_code",
            field=models.CharField(
                db_column="instructor_enroll_code",
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="Instructor Enroll Code",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="stucode",
            field=models.CharField(
                db_column="student_enroll_code",
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="Student Enroll Code",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="tascode",
            field=models.CharField(
                db_column="ta_enroll_code",
                db_index=True,
                max_length=128,
                null=True,
                verbose_name="TA Enroll Code",
            ),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="active",
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="is_independent",
            field=models.BooleanField(
                db_column="is_independent",
                db_index=True,
                default=False,
                verbose_name="is_independent?",
            ),
        ),
        migrations.AlterField(
            model_name="coursemember",
            name="role",
            field=models.CharField(
                db_column="role",
                db_index=True,
                max_length=128,
                verbose_name="User Type",
            ),
        ),
    ]
