# Generated by Django 2.1.5 on 2019-01-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peer_course", "0005_auto_20190112_2029"),
        ("peer_course", "0004_remove_coursemember_qualified"),
    ]

    operations = []
