# Generated by Django 2.1.5 on 2019-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_course", "0007_course_can_tas_see_reviews")]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enable_independent_pool",
            field=models.BooleanField(default=True),
        )
    ]
