# Generated by Django 2.1.5 on 2019-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0008_course_enable_independent_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='qualified',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
