# Generated by Django 2.1.5 on 2019-10-01 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0009_coursemember_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='time_is_independent_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
