# Generated by Django 2.1.15 on 2020-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0010_coursemember_time_is_independent_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='lower_confidence_bound',
            field=models.FloatField(db_column='lowerconfidencebound', default=1.0, null=True, verbose_name='Lower confidence bound'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='markingload',
            field=models.FloatField(db_column='markingload', default=1.0, null=True, verbose_name='Marking Load'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='upper_confidence_bound',
            field=models.FloatField(db_column='upperconfidencebound', default=1.0, null=True, verbose_name='Upper confidence bound'),
        ),
    ]
