# Generated by Django 2.1.15 on 2021-01-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0011_auto_20201221_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemember',
            name='lower_confidence_bound',
            field=models.FloatField(db_column='lowerconfidencebound', default=0.0, null=True, verbose_name='Lower confidence bound'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='markingload',
            field=models.FloatField(db_column='markingload', default=0.0, null=True, verbose_name='Marking Load'),
        ),
    ]
