# Generated by Django 2.1.15 on 2021-09-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0012_auto_20210112_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='hand_up',
            field=models.BooleanField(db_column='hand_up', db_index=True, default=False, verbose_name='hand_up'),
        ),
    ]
