# Generated by Django 2.1.15 on 2021-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0015_coursemember_participation_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='regular_points',
            field=models.IntegerField(db_column='regular_points', default=0, null=True, verbose_name='regular_points'),
        ),
    ]
