# Generated by Django 2.1.15 on 2021-09-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0016_coursemember_regular_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='first_hand_up',
            field=models.BooleanField(db_column='first_hand_up', db_index=True, default=True, verbose_name='first_hand_up'),
        ),
    ]
