# Generated by Django 2.1.15 on 2021-11-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0017_coursemember_first_hand_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable_participation',
            field=models.BooleanField(default=False),
        ),
    ]
