# Generated by Django 2.1.15 on 2021-11-25 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0018_course_enable_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='time_spoken',
            field=models.DateTimeField(db_column='time_spoken', default=django.utils.timezone.now, verbose_name='time_spoken'),
        ),
    ]
