# Generated by Django 2.1.15 on 2021-11-26 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0019_coursemember_time_spoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_participated', models.DateTimeField(db_column='time_participated', default=django.utils.timezone.now, verbose_name='time_participated')),
                ('participation_points_gained', models.IntegerField(db_column='participation_points_gained', default=0, null=True, verbose_name='participation_points_gained')),
                ('spoke_upon_participation', models.BooleanField(db_column='spoke_upon_participation', db_index=True, default=False, verbose_name='spoke_upon_participation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='peer_course.CourseMember')),
            ],
        ),
    ]
