# Generated by Django 2.1.15 on 2021-12-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0020_courseparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='hand_up_list_2',
            field=models.BooleanField(db_column='hand_up_list_2', db_index=True, default=False, verbose_name='hand_up_list_2'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='hand_up_list_3',
            field=models.BooleanField(db_column='hand_up_list_3', db_index=True, default=False, verbose_name='hand_up_list_3'),
        ),
    ]
