# Generated by Django 2.1.15 on 2021-12-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0021_auto_20211230_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipation',
            name='participation_list',
            field=models.IntegerField(db_column='participation_list', default=0, null=True, verbose_name='participation_list'),
        ),
    ]
