# Generated by Django 2.1.15 on 2022-01-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0022_courseparticipation_participation_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipation',
            name='count_in_calculations',
            field=models.BooleanField(db_column='count_in_calculations', db_index=True, default=True, verbose_name='count_in_calculations'),
        ),
    ]
