# Generated by Django 2.1.15 on 2022-01-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0024_auto_20220103_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fraction_of_points_gained_upon_further_participations',
            field=models.FloatField(db_column='fraction_of_points_gained_upon_further_participations', default=0.1, null=True, verbose_name='fraction_of_points_gained_upon_further_participations'),
        ),
    ]
