# Generated by Django 2.1.15 on 2022-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0025_course_fraction_of_points_gained_upon_further_participations'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipation',
            name='real_participation',
            field=models.BooleanField(db_column='real_participation', db_index=True, default=True, verbose_name='real_participation'),
        ),
    ]
