# Generated by Django 2.1.15 on 2023-01-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_course', '0026_courseparticipation_real_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='points_upon_participation_in_yellow_list',
            field=models.FloatField(db_column='points_upon_participation_in_yellow_list', default=0.0, null=True, verbose_name='points_upon_participation_in_yellow_list'),
        ),
        migrations.AddField(
            model_name='coursemember',
            name='hand_up_list_4',
            field=models.BooleanField(db_column='hand_up_list_4', db_index=True, default=False, verbose_name='hand_up_list_4'),
        ),
    ]
