# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 05:54
from __future__ import unicode_literals

from django.db import migrations, models


def fix_already_submitted(apps, schema_editor):
    ReviewAssignment = apps.get_model("peer_review", "ReviewAssignment")
    for review in ReviewAssignment._default_manager.all():
        if review.reviewcontent_set.exists():
            review.submitted = True
            review.save()


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0003_auto_20180822_1514")]

    operations = [
        migrations.AddField(
            model_name="reviewassignment",
            name="submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fix_already_submitted),
    ]
