# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0004_reviewassignment_submitted")]

    operations = [
        migrations.AlterField(
            model_name="reviewassignment",
            name="submitted",
            field=models.BooleanField(db_index=True, default=False),
        )
    ]
