# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peer_course", "0003_coursemember_qualified"),
        ("peer_assignment", "0008_auto_20180926_1050"),
        ("peer_review", "0005_auto_20180910_2312"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewassignment",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="peer_assignment.AssignmentQuestion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reviewassignment",
            unique_together=set([("submission", "grader", "question")]),
        ),
    ]
