# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0006_auto_20181030_2355")]

    operations = [
        migrations.AlterField(
            model_name="rubricquestionmultiplechoiceitem",
            name="marks",
            field=models.FloatField(
                blank=True,
                db_column="item_marks",
                default=0,
                verbose_name="Number of Marks",
            ),
        )
    ]
