# Generated by Django 2.1.5 on 2019-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0007_auto_20181103_1451")]

    operations = [
        migrations.AlterField(
            model_name="reviewassignment",
            name="submitted",
            field=models.BooleanField(blank=True, db_index=True, default=False),
        )
    ]
