# Generated by Django 2.1.5 on 2019-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0008_auto_20190112_1648")]

    operations = [
        migrations.AlterField(
            model_name="reviewassignment",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="reviewassignment",
            name="is_groundtruth",
            field=models.BooleanField(
                db_column="is_groundtruth",
                db_index=True,
                default=False,
                verbose_name="is_groundtruth?",
            ),
        ),
    ]
