# Generated by Django 2.1.5 on 2019-01-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("peer_review", "0009_auto_20190112_2029")]

    operations = [
        migrations.AddField(
            model_name="assignmentwithreviews",
            name="ta_reviews_per_question",
            field=models.BooleanField(
                default=False, verbose_name="Assign TA reviews per question"
            ),
        )
    ]
