# Generated by Django 2.1.5 on 2019-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0010_assignmentwithreviews_ta_reviews_per_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='assigned_grade',
            field=models.FloatField(default=0),
        ),
    ]
