# Generated by Django 2.1.5 on 2019-11-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0011_reviewassignment_assigned_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcontent',
            name='is_reason_viewed',
            field=models.BooleanField(db_column='is_reason_viewed', db_index=True, default=False, verbose_name='is_reason_viewed?'),
        ),
    ]
