# Generated by Django 2.1.5 on 2019-11-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0012_reviewcontent_is_reason_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='endorsed',
            field=models.BooleanField(db_column='endorsed', db_index=True, default=False, verbose_name='endorsed?'),
        ),
    ]
