# Generated by Django 2.1.15 on 2020-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0013_reviewassignment_endorsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='markingload',
            field=models.FloatField(db_column='reviewmarkingload', default=1.0, null=True, verbose_name='Review Marking Load'),
        ),
    ]
