# Generated by Django 2.1.15 on 2021-01-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0014_reviewassignment_markingload'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='visible',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
    ]
