# Generated by Django 2.1.15 on 2021-02-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0016_reviewcontent_component_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='timer',
            field=models.FloatField(blank=True, db_index=True, default=False),
        ),
    ]
