# Generated by Django 2.1.15 on 2021-02-08 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0017_reviewassignment_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewassignment',
            name='timer',
        ),
    ]
