# Generated by Django 2.1.15 on 2021-02-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0018_remove_reviewassignment_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='timer',
            field=models.FloatField(blank=True, db_index=True, default=False),
        ),
    ]
