# Generated by Django 2.1.15 on 2021-02-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0021_reviewassignment_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewassignment',
            name='submission_date',
        ),
    ]
