# Generated by Django 2.1.15 on 2021-03-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0023_reviewassignment_submission_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='timer',
            field=models.FloatField(blank=True, db_index=True, default=0.0),
        ),
    ]
